name: Build
set var "this string"
"this string" = "Tag Viable Invest Focus End Think Table Soon Neck Kitten Involve Blind"
on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .
